name: Generate Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create for the release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: Generate Release
    env:
      TAG: ${{ github.event.inputs.tag }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '6.0'

    - name: Build
      run: bash ./build.sh

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        declare -a files
        for file in $(ls ./build); do
          files+=("./build/$file")
        done
        gh release create -d -t "VoiDPlugins v$TAG" "$TAG" "${files[@]}"